# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'


target 'TESTS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!


   pod 'SnapKit'

  # Pods for TESTS

  target 'TESTSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TESTSUITests' do
    # Pods for testing
  end

end
